### PR TITLE
fix execute return type

### PR DESCRIPTION
**Pull request by yaacovCR**

### CODE REVIEW

**Comment by yaacovCR** [comment]
@lilianammmatos @robrichard 

This one is fairly uncontroversial, no?

**Comment by robrichard** [comment]
@yaacovCR thanks for catching this. We changed how these types work based on feedback from the GraphQL WG so I don't think this is relevant any more.

**Comment by yaacovCR** [comment]
Agree, looks like TS and flow types in sync. Thoughts on publishing these changes to graphql-experimental?

I know idea is to have separate tag within graphql package, but I am eager to get started...

**Comment by robrichard** [comment]
@yaacovCR the latest changes are published to graphql-experimental

**Comment by yaacovCR** [comment]
Amazing, thanks!

**Pull request closed without merging**
